build:
  image: ensime/ensime:latest
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
  commands:
    - git log | head -n 20
    - sbt compile
    - sbt scripted
    - if [ "$CI_BRANCH" = "master" ] ; then
        sbt publish ;
      fi
